/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package principal;

/**
 *
 * @author Samuel Cataño C
 */
public class midPrincipal extends javax.swing.JFrame {
    private jpFormCuadrado objFormCuadrado = new jpFormCuadrado();
    private jpFormCirculo objFormCirculo = new jpFormCirculo();
    private jpFormRectangulo objFormRectangulo = new jpFormRectangulo();
    private jpFormTrianguloRectangulo objFormTrianguloRectangulo = new jpFormTrianguloRectangulo();
    private jpFormRombo objFormRombo = new jpFormRombo();
    private jpFormTrapecio objFormTrapecio = new jpFormTrapecio();
    
    private void inicializarFormularios(){
        jifFormCuadrado.setContentPane(objFormCuadrado);
        objFormCuadrado.setSize(300,300);
        jifFormCuadrado.setSize(300,330);
        
        jifFormCirculo.setContentPane(objFormCirculo);
        objFormCirculo.setSize(300,300);
        jifFormCirculo.setSize(300,330);
        
        jifFormRectangulo.setContentPane(objFormRectangulo);
        objFormRectangulo.setSize(300,300);
        jifFormRectangulo.setSize(300,330);
        
        jifFormTrianguloRectangulo.setContentPane(objFormTrianguloRectangulo);
        objFormTrianguloRectangulo.setSize(300,300);
        jifFormTrianguloRectangulo.setSize(300,330);
        
        jifFormRombo.setContentPane(objFormRombo);
        objFormRombo.setSize(300,300);
        jifFormRombo.setSize(300,330);
        
        jifFormTrapecio.setContentPane(objFormTrapecio);
        objFormTrapecio.setSize(300,300);
        jifFormTrapecio.setSize(300,330);
    }
    /**
     * Creates new form midPrincipal
     */
    public midPrincipal() {
        initComponents();
        this.inicializarFormularios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifFormCuadrado = new javax.swing.JInternalFrame();
        jifFormCirculo = new javax.swing.JInternalFrame();
        jifFormRectangulo = new javax.swing.JInternalFrame();
        jifFormTrianguloRectangulo = new javax.swing.JInternalFrame();
        jifFormRombo = new javax.swing.JInternalFrame();
        jifFormTrapecio = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jmiFormCuadrado = new javax.swing.JMenuItem();
        jmiFormCirculo = new javax.swing.JMenuItem();
        jmiFormRectangulo = new javax.swing.JMenuItem();
        jmiFormTrianguloRectangulo = new javax.swing.JMenuItem();
        jmiFormRombo = new javax.swing.JMenuItem();
        jmiFormTrapecio = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifFormCuadrado.setClosable(true);
        jifFormCuadrado.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormCuadrado.setVisible(false);

        javax.swing.GroupLayout jifFormCuadradoLayout = new javax.swing.GroupLayout(jifFormCuadrado.getContentPane());
        jifFormCuadrado.getContentPane().setLayout(jifFormCuadradoLayout);
        jifFormCuadradoLayout.setHorizontalGroup(
            jifFormCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormCuadradoLayout.setVerticalGroup(
            jifFormCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormCuadrado);
        jifFormCuadrado.setBounds(10, 10, 370, 340);

        jifFormCirculo.setClosable(true);
        jifFormCirculo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormCirculo.setVisible(false);

        javax.swing.GroupLayout jifFormCirculoLayout = new javax.swing.GroupLayout(jifFormCirculo.getContentPane());
        jifFormCirculo.getContentPane().setLayout(jifFormCirculoLayout);
        jifFormCirculoLayout.setHorizontalGroup(
            jifFormCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormCirculoLayout.setVerticalGroup(
            jifFormCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormCirculo);
        jifFormCirculo.setBounds(10, 0, 370, 370);

        jifFormRectangulo.setClosable(true);
        jifFormRectangulo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormRectangulo.setVisible(false);

        javax.swing.GroupLayout jifFormRectanguloLayout = new javax.swing.GroupLayout(jifFormRectangulo.getContentPane());
        jifFormRectangulo.getContentPane().setLayout(jifFormRectanguloLayout);
        jifFormRectanguloLayout.setHorizontalGroup(
            jifFormRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormRectanguloLayout.setVerticalGroup(
            jifFormRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormRectangulo);
        jifFormRectangulo.setBounds(10, 10, 390, 350);

        jifFormTrianguloRectangulo.setClosable(true);
        jifFormTrianguloRectangulo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormTrianguloRectangulo.setVisible(false);

        javax.swing.GroupLayout jifFormTrianguloRectanguloLayout = new javax.swing.GroupLayout(jifFormTrianguloRectangulo.getContentPane());
        jifFormTrianguloRectangulo.getContentPane().setLayout(jifFormTrianguloRectanguloLayout);
        jifFormTrianguloRectanguloLayout.setHorizontalGroup(
            jifFormTrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormTrianguloRectanguloLayout.setVerticalGroup(
            jifFormTrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormTrianguloRectangulo);
        jifFormTrianguloRectangulo.setBounds(0, 10, 400, 330);

        jifFormRombo.setClosable(true);
        jifFormRombo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormRombo.setVisible(false);

        javax.swing.GroupLayout jifFormRomboLayout = new javax.swing.GroupLayout(jifFormRombo.getContentPane());
        jifFormRombo.getContentPane().setLayout(jifFormRomboLayout);
        jifFormRomboLayout.setHorizontalGroup(
            jifFormRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormRomboLayout.setVerticalGroup(
            jifFormRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormRombo);
        jifFormRombo.setBounds(0, 0, 300, 180);

        jifFormTrapecio.setClosable(true);
        jifFormTrapecio.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormTrapecio.setVisible(false);

        javax.swing.GroupLayout jifFormTrapecioLayout = new javax.swing.GroupLayout(jifFormTrapecio.getContentPane());
        jifFormTrapecio.getContentPane().setLayout(jifFormTrapecioLayout);
        jifFormTrapecioLayout.setHorizontalGroup(
            jifFormTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormTrapecioLayout.setVerticalGroup(
            jifFormTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormTrapecio);
        jifFormTrapecio.setBounds(0, 0, 280, 180);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        jmiFormCuadrado.setText("Cuadrado");
        jmiFormCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormCuadradoActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormCuadrado);

        jmiFormCirculo.setText("Círculo");
        jmiFormCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormCirculoActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormCirculo);

        jmiFormRectangulo.setText("Rectángulo");
        jmiFormRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormRectanguloActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormRectangulo);

        jmiFormTrianguloRectangulo.setText("Triángulo rectángulo");
        jmiFormTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormTrianguloRectanguloActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormTrianguloRectangulo);

        jmiFormRombo.setText("Rombo");
        jmiFormRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormRomboActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormRombo);

        jmiFormTrapecio.setText("Trapecio");
        jmiFormTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormTrapecioActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormTrapecio);

        jmiSalir.setMnemonic('x');
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        fileMenu.add(jmiSalir);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiFormCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormCuadradoActionPerformed
        // TODO add your handling code here:
        jifFormCuadrado.setVisible(true);
    }//GEN-LAST:event_jmiFormCuadradoActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void jmiFormCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormCirculoActionPerformed
        // TODO add your handling code here:
        jifFormCirculo.setVisible(true);
    }//GEN-LAST:event_jmiFormCirculoActionPerformed

    private void jmiFormRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormRectanguloActionPerformed
        // TODO add your handling code here:
        jifFormRectangulo.setVisible(true);
    }//GEN-LAST:event_jmiFormRectanguloActionPerformed

    private void jmiFormTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormTrianguloRectanguloActionPerformed
        // TODO add your handling code here:
        jifFormTrianguloRectangulo.setVisible(true);
    }//GEN-LAST:event_jmiFormTrianguloRectanguloActionPerformed

    private void jmiFormRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormRomboActionPerformed
        jifFormRombo.setVisible(true);
    }//GEN-LAST:event_jmiFormRomboActionPerformed

    private void jmiFormTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormTrapecioActionPerformed
        jifFormTrapecio.setVisible(true);
    }//GEN-LAST:event_jmiFormTrapecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(midPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(midPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(midPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(midPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new midPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JInternalFrame jifFormCirculo;
    private javax.swing.JInternalFrame jifFormCuadrado;
    private javax.swing.JInternalFrame jifFormRectangulo;
    private javax.swing.JInternalFrame jifFormRombo;
    private javax.swing.JInternalFrame jifFormTrapecio;
    private javax.swing.JInternalFrame jifFormTrianguloRectangulo;
    private javax.swing.JMenuItem jmiFormCirculo;
    private javax.swing.JMenuItem jmiFormCuadrado;
    private javax.swing.JMenuItem jmiFormRectangulo;
    private javax.swing.JMenuItem jmiFormRombo;
    private javax.swing.JMenuItem jmiFormTrapecio;
    private javax.swing.JMenuItem jmiFormTrianguloRectangulo;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
